### ISSUE TITLE
Configure eq-3 bluetooth device

### ISSUE THREAD

**Issue by DanyColorado** [alikh31/node-red-contrib-eq3-bluetooth#5]
I would like to set the e.g. Temperature. The readout works fine, but i can't change the setpoint, system mode etc.
I'm newbie in node-red, and javascript, I would like to ask for an example flow, to changing parameters.

Thank You!

**Comment by janvda** [comment]
Regarding the sample flows: see  https://github.com/janvda/node-red-eq3

Is it OK to close this issue ?
