### ISSUE TITLE
connection sync failure

### ISSUE THREAD

**Issue by sanober-pm** [alikh31/node-red-contrib-eq3-bluetooth#9]
Hi, I am new to postman and I have been seeing some issues like :-
1.  my postman collection is not syncing. (It was few months ago)
2. A week ago some of my requests went blank
3. app was not updating to the latest version
4. I tried re-installing the app and now its showing as connecting on the right most corner, coz of which my workspace is not downloading (NOTE - I do see my collection online)

Appreciate all the help!!!

**Comment by alikh31** [comment]
sorry but I think you are in the wrong repo :)
